server:
  port: 8083

spring:
  data:
    mongodb:
      authentication-database: admin
      database: library
      port: 27017
      host: localhost
      username: nursd
      password: Madinka2403

mongock:
  change-logs-scan-package: ru.otus.library.db

#logging:
#  level:
#    ROOT: ERROR