server:
  port: 8083

spring:
  data:
    mongodb:
      authentication-database: admin
      database: library
      port: 27017
      host: localhost
      username: nursd
      password: Madinka2403

#logging:
#  level:
#    ROOT: ERROR